### ISSUE TITLE
Profile | Make first alphabet of name capital

### ISSUE THREAD

**Issue by rohitrvayuz** [rgnarok/VLCC-issue-tracker#31]
![Screenshot_2021-11-11-12-19-05-306_com_example_vlcc](https://user-images.githubusercontent.com/78350161/141260075-673a0450-4f6e-4101-b6f8-3e80f5cc780d.jpg)

**Comment by ShikharVayuz** [comment]
Fixed

**Comment by rohitrvayuz** [comment]
@ShikharVayuz @Shaktivayuz  Please add review label when done

**Comment by rohitrvayuz** [comment]
This is fixed.
