### ISSUE TITLE
Search Page | On denying location permission it shows the labels as 'sub laoclity' etc. iT SHOULD A DEFAULT CITY NAME lIKE New Delhi

### ISSUE THREAD

**Issue by rohitrvayuz** [rgnarok/VLCC-issue-tracker#33]
![Screenshot_2021-11-11-12-20-27-808_com_example_vlcc](https://user-images.githubusercontent.com/78350161/141260340-b39432a4-2ffe-4959-b24d-fed5850af2b8.jpg)

**Comment by Shaktivayuz** [comment]
Done

**Comment by rohitrvayuz** [comment]
This is fixed.
