### ISSUE TITLE
App > Dashboard >Replace Dashboard with VLCC logo and Reduce the icon size for Notification and user Icon > Check SS

### ISSUE THREAD

**Issue by Arushiv13** [rgnarok/VLCC-issue-tracker#39]
![MicrosoftTeams-image (44)](https://user-images.githubusercontent.com/94099426/141291129-fa8e0ba6-4ee5-4f53-9a8b-f6bdbf9a0bed.png)

**Comment by rohitrvayuz** [comment]
@Arushiv13 This matches the figma design. Only alignment has to be made to the left side.
@Shaktivayuz  Please check this
