### ISSUE TITLE
App > Notifications  UI > Check Description

### ISSUE THREAD

**Issue by Arushiv13** [rgnarok/VLCC-issue-tracker#40]
1. Back Button is not aligned / Check SS 
2. Reduce the icon size for mark all as read 
3. Mark all as read is not working 
![Uploading MicrosoftTeams-image (43).png…]()

**Comment by ShikharVayuz** [comment]
@Arushiv13 Notifications screen has not been integrated yet. We are waiting for the api from the vlcc team.
